export const keys = {
  donor: {
    all: ["donor"],
    list: (page, limit) => ["donor", "list", page, limit],
    inactive: ["donor", "inactive"],
    discarded: ["donor", "discarded"],
    byId: (id) => ["donor", id],
    otherTest: (id) => ["donor", "otherTest", id],
  },
  milkVolume: {
    all: ["milkVolume"],
    list: ["milkVolume", "list"],
    byDonor: (id) => ["milkVolume", "byDonor", id],
    milkList: (id) => ["milkVolume", "milkList", id],
    donorWithTotal: ["milkVolume", "donorWithTotal"],
    collectedForDonor: (id) => ["milkVolume", "collected", id],
  },
  pasteurization: {
    all: ["pasteurization"],
    list: ["pasteurization", "list"],
    byId: (id) => ["pasteurization", id],
    colostrum: ["pasteurization", "colostrum"],
    condition: ["pasteurization", "condition"],
    conditionById: (id) => ["pasteurization", "condition", id],
    donorByGestational: (id) => ["pasteurization", "donorByGestational", id],
  },
  baby: {
    all: ["baby"],
    list: ["baby", "list"],
    inactive: ["baby", "inactive"],
    byId: (id) => ["baby", id],
    ipList: ["baby", "ipList"],
  },
  milkRequisition: {
    all: ["milkRequisition"],
    list: ["milkRequisition", "list"],
    byId: (id) => ["milkRequisition", id],
  },
  office: {
    list: ["office", "list"],
    department: ["office", "department"],
    departmentById: (id) => ["office", "department", id],
    post: ["office", "post"],
    postById: (id) => ["office", "post", id],
    employee: ["office", "employee"],
    employeeById: (id) => ["office", "employee", id],
    fiscal: ["office", "fiscal"],
    fiscalById: (id) => ["office", "fiscal", id],
    state: ["office", "state"],
    district: (stateId) => ["office", "district", stateId],
    palika: (districtId) => ["office", "palika", districtId],
    donation: ["office", "donation"],
    donationById: (id) => ["office", "donation", id],
  },
  user: {
    all: ["user", "all"],
    byId: (id) => ["user", id],
    modules: ["user", "modules"],
  },
  dashboard: {
    allRecords: ["dashboard", "allRecords"],
    milkCollectionMonthly: ["dashboard", "milkCollectionMonthly"],
    milkRequisitionMonthly: ["dashboard", "milkRequisitionMonthly"],
    donorNumberMonthly: ["dashboard", "donorNumberMonthly"],
  },
  dropdown: {
    gestational: ["dropdown", "gestational"],
    gestationalTwo: ["dropdown", "gestationalTwo"],
    parity: ["dropdown", "parity"],
    delivery: ["dropdown", "delivery"],
    ethnicity: ["dropdown", "ethnicity"],
    babyStatus: ["dropdown", "babyStatus"],
    babyTransfer: ["dropdown", "babyTransfer"],
    breastFeeding: ["dropdown", "breastFeeding"],
    babyOutcome: ["dropdown", "babyOutcome"],
  },
  report: {
    all: ["report", "all"],
    dateWise: (from, to) => ["report", "dateWise", from, to],
    milkDiscard: ["report", "milkDiscard"],
    milkDiscardDateWise: (from, to) => ["report", "milkDiscardDateWise", from, to],
  },
  bottle: {
    byId: (id) => ["bottle", id],
  },
};
