export const urls = {
  getStates: `/api/office/state`,
  getDistrict: `/api/office/district`,
  getPalika: `/api/office/palika`,
  getGestational: `/api/dropdown/gestational`,
  getBabyStatus: `/api/dropdown/babyStatus`,
  getBabyTransfer: `/api/dropdown/babyTransfer`,
  getBreastFeeding: `/api/dropdown/breastFeeding`,
  getDelivery: `/api/dropdown/delivery`,
  getParity: `/api/dropdown/parity`,
  getEthnicity: `/api/dropdown/ethnicity`,
  login: `/api/user/login`,
  register: `/api/user/register`,
  createOffice: `/api/office/createOffice`,
  getOffice: `/api/office/getOffice`,
  createDepartment: `/api/office/department/createDepartment`,
  getDepartment: `/api/office/department/getDepartment`,
  createPost: `/api/office/post/createPost`,
  getPost: `/api/office/post/getPost`,
  createEmployee: `/api/office/employee/createEmployee`,
  getEmployee: `/api/office/employee/getEmployee`,
  createVolumeOfMilk: `/api/volumeOfMilk/addVolumeOfMilk`,
  getDonor: `/api/daanDartaRecord/get`,
  createDanaDarta: `/api/daanDartaRecord/create`,
  getVolumeOfMilk:`/api/volumeOfMilk/getVolumeOfMilk`,

};
