import SideBar from "../../../components/SideBar";
import { Inter } from "next/font/google";
import "../../globals.css";
import Navbar from "@/components/navbar";
import Footer from "src/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex `}>
        <Navbar />
        <SideBar />
        <main className="md:ml-60 mb-10">
          {children}
          <div className="flex justify-center mt-10  ">
            <Footer />
          </div>
        </main>
      </body>
    </html>
  );
}
